In [ ]:
import numpy as np
X = np.array(([2,9],[1,5],[3,6]),dtype=float)
Y = np.array(([92],[86],[89]),dtype=float)
X = X/np.amax(X,axis=0)
actual_output = Y/100
print(X)
print(actual_output)


[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [ ]:
def sigmoid(x):
  return (1/(1+np.exp(-x)))
def derivatives_sigmoid(x):
  return x * (1-x)

epoch = 5000
lr =0.15
ipn=2
hn=3
opn=1
wh = np.random.uniform(low=-0.05,high=0.05,size=(ipn,hn))
bh = np.random.uniform(low=-0.05,high=0.05,size=(1,hn))
wo = np.random.uniform(low=-0.05,high=0.05,size=(hn,opn))
bo = np.random.uniform(low=-0.05,high=0.05,size=(1,opn))
for i in range(epoch):
  net_h = np.dot(X,wh) + bh
  sigma_h = sigmoid(net_h)
  net_o = np.dot(sigma_h,wo) + bo
  output = sigmoid(net_o)

  eo = actual_output-output
  outgrad = derivatives_sigmoid(output)
  d_output = eo*outgrad
  eh = d_output.dot(wo.T)
  hiddengrad = derivatives_sigmoid(sigma_h)
  d_hidden = eh*hiddengrad
  wo += sigma_h.T.dot(d_output)*lr
  wh += X.T.dot(d_hidden)*lr
  sum_error = 0
  for j in range(len(actual_output)):
    sum_error += output[j]-actual_output[j]
  sum_error/=2
print("Normalized Input: \n",str(X))
print("Actual_output: \n",str(actual_ouput))
print("Predicted output:\n",output) 



Normalized Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual_output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted output:
 [[0.89793523]
 [0.87632195]
 [0.89576695]]
