In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=23)
print(iris.data.shape)
print("Training Set:",len(X_train))
print("Testing set:",len(X_test))

(150, 4)
Training Set: 120
Testing set: 30


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
y_pred

array([2, 2, 1, 0, 2, 1, 0, 2, 0, 1, 1, 0, 2, 0, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 0, 2, 0, 0, 2, 1, 1])

In [ ]:
from sklearn import metrics
print("Accuracy: ",metrics.accuracy_score(y_pred,y_test))
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy:  0.9666666666666667
[[12  0  0]
 [ 0  8  0]
 [ 0  1  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.89      1.00      0.94         8
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
predicted = knn.predict(X_test)
pre_target = [iris.target_names[i] for i in predicted]
print("pre_target: ",pre_target,"\n\n")
actual_target = [ iris.target_names[i] for i in y_test]
print("actual_target: ",actual_target,"\n\n")
print("\tpredicted\t\tActual\t\t\tAnswer")
for i in range(0,len(pre_target)):
  print(i,":\t",pre_target[i],"\t\t",actual_target[i],"\t",end='\t')
  if(pre_target[i]==actual_target[i]):
    print("yes")
  else:
    print("No")

pre_target:  ['virginica', 'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor', 'versicolor', 'setosa', 'virginica', 'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica', 'setosa', 'virginica', 'setosa', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor'] 


actual_target:  ['virginica', 'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor', 'versicolor', 'setosa', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa', 'virginica', 'setosa', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor'] 


	predicted		Actual			Answer
0 :	 virginica 		 virginica 		yes
1 :	 virginica 		 virginica 		yes
2 :	 versicolor 		 versicolor 		yes
3 :	 setosa 		 setosa 		yes
4 :	 virginica 		 virginica 		yes
5 :	 versicolor 		 versicolor 		yes
6 :	 set